// <auto-generated />
using System;
using HSMS.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HSMS.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("HSMS.Core.Entities.DeliveryTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DispatchTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("RequisitionId")
                        .IsUnique();

                    b.ToTable("DeliveryTasks", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.InventoryRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchLotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationBin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("RecordId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseId", "ItemId");

                    b.ToTable("InventoryRecords", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpecificationText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.ItemWarehouseProfile", b =>
                {
                    b.Property<Guid>("ItemWarehouseProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReorderPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafetyStockCeiling")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemWarehouseProfileId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("ItemWarehouseProfiles", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.PickList", b =>
                {
                    b.Property<Guid>("PickListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GeneratedById")
                        .HasColumnType("TEXT");

                    b.Property<int>("PickStatus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("PickListId");

                    b.HasIndex("GeneratedById");

                    b.HasIndex("RequisitionId");

                    b.ToTable("PickLists", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.Requisition", b =>
                {
                    b.Property<Guid>("RequisitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequisitionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequisitionId");

                    b.HasIndex("RequestDate");

                    b.HasIndex("RequestedById");

                    b.HasIndex("Status");

                    b.ToTable("Requisitions", (string)null);

                    b.HasDiscriminator<string>("RequisitionType").HasValue("Requisition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HSMS.Core.Entities.RequisitionLineItem", b =>
                {
                    b.Property<Guid>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("FulfilledQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.HasKey("LineItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionLineItems", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.StockTransferLine", b =>
                {
                    b.Property<Guid>("StockTransferLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StockTransferOrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("StockTransferLineId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockTransferOrderId");

                    b.ToTable("StockTransferLines", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.StockTransferOrder", b =>
                {
                    b.Property<Guid>("StockTransferOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DestinationWarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceWarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockTransferOrderId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SourceWarehouseId");

                    b.HasIndex("Status");

                    b.ToTable("StockTransferOrders", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HSMS.Core.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCentralHub")
                        .HasColumnType("INTEGER");

                    b.HasKey("WarehouseId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("HSMS.Core.Entities.EmergencyRequisition", b =>
                {
                    b.HasBaseType("HSMS.Core.Entities.Requisition");

                    b.Property<string>("JustificationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("EmergencyRequisition");
                });

            modelBuilder.Entity("HSMS.Core.Entities.StandardRequisition", b =>
                {
                    b.HasBaseType("HSMS.Core.Entities.Requisition");

                    b.Property<string>("TargetDeliveryWindow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("StandardRequisition");
                });

            modelBuilder.Entity("HSMS.Core.Entities.InventoryManager", b =>
                {
                    b.HasBaseType("HSMS.Core.Entities.User");

                    b.Property<string>("AssignedWarehouseZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("InventoryManager");
                });

            modelBuilder.Entity("HSMS.Core.Entities.LogisticsStaff", b =>
                {
                    b.HasBaseType("HSMS.Core.Entities.User");

                    b.Property<string>("ActiveVehicleId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("LogisticsStaff");
                });

            modelBuilder.Entity("HSMS.Core.Entities.MedicalStaff", b =>
                {
                    b.HasBaseType("HSMS.Core.Entities.User");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MedicalStaff");
                });

            modelBuilder.Entity("HSMS.Core.Entities.DeliveryTask", b =>
                {
                    b.HasOne("HSMS.Core.Entities.LogisticsStaff", "AssignedTo")
                        .WithMany("DeliveryTasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HSMS.Core.Entities.Requisition", "Requisition")
                        .WithOne("DeliveryTask")
                        .HasForeignKey("HSMS.Core.Entities.DeliveryTask", "RequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("HSMS.Core.Entities.InventoryRecord", b =>
                {
                    b.HasOne("HSMS.Core.Entities.Item", "Item")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSMS.Core.Entities.Warehouse", "Warehouse")
                        .WithMany("InventoryRecords")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("HSMS.Core.Entities.ItemWarehouseProfile", b =>
                {
                    b.HasOne("HSMS.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSMS.Core.Entities.Warehouse", "Warehouse")
                        .WithMany("ItemWarehouseProfiles")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("HSMS.Core.Entities.PickList", b =>
                {
                    b.HasOne("HSMS.Core.Entities.InventoryManager", "GeneratedBy")
                        .WithMany("PickLists")
                        .HasForeignKey("GeneratedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSMS.Core.Entities.Requisition", "Requisition")
                        .WithMany("PickLists")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedBy");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("HSMS.Core.Entities.Requisition", b =>
                {
                    b.HasOne("HSMS.Core.Entities.User", "RequestedBy")
                        .WithMany("Requisitions")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("HSMS.Core.Entities.RequisitionLineItem", b =>
                {
                    b.HasOne("HSMS.Core.Entities.Item", "Item")
                        .WithMany("RequisitionLineItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSMS.Core.Entities.Requisition", "Requisition")
                        .WithMany("RequisitionLineItems")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("HSMS.Core.Entities.StockTransferLine", b =>
                {
                    b.HasOne("HSMS.Core.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSMS.Core.Entities.StockTransferOrder", "StockTransferOrder")
                        .WithMany("Lines")
                        .HasForeignKey("StockTransferOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("StockTransferOrder");
                });

            modelBuilder.Entity("HSMS.Core.Entities.StockTransferOrder", b =>
                {
                    b.HasOne("HSMS.Core.Entities.User", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HSMS.Core.Entities.Warehouse", "DestinationWarehouse")
                        .WithMany("InboundTransfers")
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSMS.Core.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HSMS.Core.Entities.Warehouse", "SourceWarehouse")
                        .WithMany("OutboundTransfers")
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompletedBy");

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("RequestedBy");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("HSMS.Core.Entities.Item", b =>
                {
                    b.Navigation("InventoryRecords");

                    b.Navigation("RequisitionLineItems");
                });

            modelBuilder.Entity("HSMS.Core.Entities.Requisition", b =>
                {
                    b.Navigation("DeliveryTask");

                    b.Navigation("PickLists");

                    b.Navigation("RequisitionLineItems");
                });

            modelBuilder.Entity("HSMS.Core.Entities.StockTransferOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("HSMS.Core.Entities.User", b =>
                {
                    b.Navigation("Requisitions");
                });

            modelBuilder.Entity("HSMS.Core.Entities.Warehouse", b =>
                {
                    b.Navigation("InboundTransfers");

                    b.Navigation("InventoryRecords");

                    b.Navigation("ItemWarehouseProfiles");

                    b.Navigation("OutboundTransfers");
                });

            modelBuilder.Entity("HSMS.Core.Entities.InventoryManager", b =>
                {
                    b.Navigation("PickLists");
                });

            modelBuilder.Entity("HSMS.Core.Entities.LogisticsStaff", b =>
                {
                    b.Navigation("DeliveryTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
